version:
  @project.version@
server:
  port: 7788
spring:
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
  resources:
    static-locations: classpath:/static/
  http:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:h2:mem:mall;DB_CLOSE_DELAY=-1
    username: sa
    password:
 #   schema:
 #     - classpath:sql/load_script.sql
 #   sql-script-encoding: utf-8
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  h2:
    console:
      web-allow-others: true
      path: /h2-console
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: 993e7a590cf0